### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [AnandChowdhary/staart#1]
Hi @AnandChowdhary I am a logo designer. 

I contribute to open source projects that do not have logo.  I have designed a logo for staart. The logo idea also represents the function of the software. What do you think? 

![staart](https://user-images.githubusercontent.com/36298335/56811018-70bad980-6840-11e9-9401-f8c449999981.jpg)

**Comment by AnandChowdhary** [comment]
Hi @reallinfo, thanks for the contribution!

I love the icon, but I'd like to change the type to go with some of my other projects' logos (https://github.com/AnandChowdhary/hello-bar and https://github.com/AnandChowdhary/hovercard).

![Updated version of logo](https://user-images.githubusercontent.com/2841780/56848024-4846e400-6901-11e9-92f3-1872346c664d.png)

Would love to hear what you think!

**Comment by reallinfo** [comment]
Yeah, the font is fine. how about making such a change? My opinion, The fact that the marked places are discrete provides the icon and typeface integrity. I still respect your opinion. Just suggestion. Btw, would you please tell me the name of the font? I can send you a pr for source files.

**Comment by AnandChowdhary** [comment]
Sure, sounds great! It’s an edited version of Proxima Nova but I think you can use Proxima Nova Rounded Medium and it should be exactly what you want.

**Comment by reallinfo** [comment]
Oh okay, by the way, what is proxima nova's license? Are you sure we can use it?

**Comment by AnandChowdhary** [comment]
This is Proxima Nova Soft Medium. If you own a desktop use license, you can use it for logos:

![soft](https://user-images.githubusercontent.com/2841780/56851206-f4042a00-6929-11e9-96af-cc3543f9199b.png)

**Comment by reallinfo** [comment]
Wow, looks great. honestly, I'm afraid to violate the licensing rules. Also, I think this font is paid font. but don't worry. I found a very similar font. Can we use this font if you don't mind?  [FREE FONT:quicksand bold](https://www.dafont.com/quicksand.font)

![start](https://user-images.githubusercontent.com/36298335/56854771-9d581980-6944-11e9-84fe-42e7a4ef64c0.jpg)

**Comment by AnandChowdhary** [comment]
I have purchased a license. I think it's worth it to get Proxima Soft 😉

**Comment by reallinfo** [comment]
Oh okay, If I had a license, I was going to handle all the arrangements. I added the ai file to the google drive. is there anything else you want from me? https://drive.google.com/open?id=1Yh6_Lh54WptJcQXZCxss_XQmnmfuUoaX

**Comment by AnandChowdhary** [comment]
Nope, I'll just add the text, change the colors a bit (I don't like the Node.js dark green, but a similar shade) and add it to README.md with credit to you.

**Comment by reallinfo** [comment]
Thanks! if you need help with other projects, don't hesitate to contact me. Have a nice day!

**Comment by AnandChowdhary** [comment]
@all-contributors please add @reallinfo for design

**Comment by AnandChowdhary** [comment]
@all-contributors please add @reallinfo for design
